#!/bin/bash

DB_NAME="arXiv"
COLLECTION="papers"

for file in $(ls data_chunk_*.ndjson 2>/dev/null | sort -V); do
	mongoimport --db "$DB_NAME" --collection "$COLLECTION" --file "$file" --type=json
done
